package constants

const API_ROUTER_STABLE = "/api/" + "v1" + "/system" + "/nofify"

var REDIS_KEYS = [1]string{"auth:register_otp"}

const ENV_RABBITMQ_URL = "RABBITMQ_URL"

const ENV_CHANELRABBITMQ_NOTIFY_TOPIC = "CHANELRABBITMQ_NOTIFY_TOPIC"
const ENV_CHANELRABBITMQ_NOTIFY_RMSG = "CHANELRABBITMQ_NOTIFY_MSG"

const ENV_CREDENTIALS_EMAIL_PROVIDER = "CREDENTIALS_EMAIL_PROVIDER"
const ENV_CREDENTIALS_FROM_EMAIL_PROVIDER = "CREDENTIALS_FROM_EMAIL_PROVIDER"
