[build]
cmd = "go build -o ./tmp/main.exe ./cmd/main.go"

bin = "./tmp/main.exe"

include_dir = ["cmd", "internal", "pkg"]

include_ext = ["go", "tpl", "tmpl", "html", "json"]

exclude_dir = ["assets", "tmp", "vendor", "docs"]
